### ISSUE TITLE
Quantified Code Badge is incorrect

### ISSUE THREAD

**Issue by DavidEBest** [18F/ekip-api#224]
The badge in this project's README refers to an out-of-date fork (@NoahKunin's) and not the 18F source of the code.

The results have improved since the fork was created.

What's shown in the README for this project:
<img width="185" alt="screenshot 2015-12-28 11 33 06" src="https://cloud.githubusercontent.com/assets/933586/12021705/ec3ffa34-ad56-11e5-8f61-4358654254af.png">

What it should show:
<img width="178" alt="screenshot 2015-12-28 11 33 13" src="https://cloud.githubusercontent.com/assets/933586/12021704/ec3d5342-ad56-11e5-9b0a-f5643f527fd0.png">

**Comment by OpenGlobe** [comment]
Hey @cacraig - can you take a look at this when you have a moment?

**Comment by cmc333333** [comment]
@OpenGlobe / @cacraig the issue is that the badge shown refers to Noah's _fork_:
<img width="690" alt="screen shot 2016-08-01 at 4 38 44 pm" src="https://cloud.githubusercontent.com/assets/326918/17308171/a32032b4-5806-11e6-8887-e79173621b47.png">

We should have one set up for the 18F fork instead and refer to that. Does that make sense? You can login to Quantified Code with your Github handles to set this up if you haven't already

**Comment by OpenGlobe** [comment]
Thanks @cmc333333 !  Yeah, that answers my question - I wasn't sure if we should login to Quantified Code or if there was another account we should be using instead.
